// AUTO-GENERATED by supabaseSync.js — do not edit directly

export const templates = {
  Email Intro: {
    subjectA: "{{dealName}} - {{dealType}}, {{sector}}",
    subjectB: "{{firstName}}, quick question on {{dealName}}",
    body: "{{firstName}},\n\nI am working on {{dealName}}, a {{dealType}} in the {{sector}} space generating ${{ebitda}}M EBITDA at a ${{ev}}M enterprise value.\n\nGiven your focus on {{investorFocus}}, I believe this fits your mandate well.\n\nHappy to send across the executive summary if this is of interest to you.\n\n{{senderName}}",
  },
  Email Follow Up: {
    subjectA: "Re: {{dealName}}",
    subjectB: "{{firstName}}, last note on {{dealName}}",
    body: "{{firstName}},\n\nWanted to follow up on {{dealName}}. The process is moving and I wanted to make sure you had visibility before we progress.\n\nThis is an exclusive mandate and I am reaching out to a small number of investors whose profile aligns with the deal.\n\nWorth a quick conversation?\n\n{{senderName}}",
  },
};

export function applyTemplate(templateObj, data) {
  const result = {};
  for (const key of Object.keys(templateObj)) {
    let value = templateObj[key];
    for (const [placeholder, replacement] of Object.entries(data)) {
      value = value.replace(new RegExp(`\\{\\{${placeholder}\\}\\}`, 'g'), replacement || '');
    }
    result[key] = value;
  }
  return result;
}