#!/bin/bash
echo "Roco Supabase Setup"
echo "==================="
echo ""
echo "Project already configured: https://xunqaxmqdknlrqdztepw.supabase.co"
echo ""
echo "If you need to re-run the schema setup:"
echo "1. Go to: https://supabase.com/dashboard/project/xunqaxmqdknlrqdztepw/sql"
echo "2. Paste the contents of scripts/setupSupabase.sql"
echo "3. Run it — all tables will be created or updated safely"
echo ""
echo "IMPORTANT: Use the SERVICE ROLE key (already in .env as SUPABASE_SERVICE_KEY)"
echo "Never expose this key to the browser or any frontend."
echo ""
echo "Current credentials in .env:"
grep "^SUPABASE_URL" /root/roco/.env 2>/dev/null && echo "SUPABASE_URL: set" || echo "SUPABASE_URL: MISSING"
grep "^SUPABASE_SERVICE_KEY" /root/roco/.env 2>/dev/null && echo "SUPABASE_SERVICE_KEY: set" || echo "SUPABASE_SERVICE_KEY: MISSING"
echo ""
echo "To restart Roco with Supabase: pm2 restart roco"
